// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzl6wdtPvalrz-xwB0WFyuyTOU9XmKyhg',
    appId: '1:406206308499:web:71c80859c811d539196d66',
    messagingSenderId: '406206308499',
    projectId: 'reddit-clone-r-f75ce',
    authDomain: 'reddit-clone-r-f75ce.firebaseapp.com',
    storageBucket: 'reddit-clone-r-f75ce.firebasestorage.app',
    measurementId: 'G-KDNPM6R8W7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2jBmhdragpCMZillj49szZ7mvd_qjytA',
    appId: '1:406206308499:android:33f9db7479e2c717196d66',
    messagingSenderId: '406206308499',
    projectId: 'reddit-clone-r-f75ce',
    storageBucket: 'reddit-clone-r-f75ce.firebasestorage.app',
  );
}
